name: Run Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testcase:
          - test_cal.py
          - test_index.py
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py310 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest -v -s tests/${{ matrix.testcase }} --alluredir=./allure-results
        continue-on-error: true
      - name: Generate Coverage Report
        run: |
          coverage report -m
      - name: Display files and path
        run: |
          ls
          pwd
      - name: Display allure files and path
        run: |
          cd allure-results
          ls
          pwd
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.testcase }}-${{ github.run_id }}
          path: allure-results
          retention-days: 5

      - name: Display allure files and path
        run: |
          ls
          pwd
          cd allure-results
          ls
          pwd

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get log files
        uses: actions/download-artifact@v4
        with:
          name: allure raw log
          path: ./allure-results
      - name: Display allure files and path
        run: |
          ls
          pwd
          cd allure-results
          ls
          pwd



      # - name: allure-html-report-s3-website
      #   uses: PavanMudigonda/allure-html-report-aws-s3-website@v1.0
      #   with:
      #     report_url: http://${{ secrets.AWS_S3_BUCKET }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com
      #     allure_results: allure-results
      #     allure_history: allure-history
      #     allure_report: allure-report
      #     keep_reports: 10
      #     args: --acl public-read --follow-symlinks
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
      #     SOURCE_DIR: 'allure-history'      # optional: defaults to entire repository
      #     # DEST_DIR: ${{ env.GITHUB_RUN_NUMBER }}
      # - name: Post the link to the report
      #   if: always()
      #   uses: Sibz/github-status-action@v1 
      #   with: 
      #       authToken: ${{secrets.GITHUB_TOKEN}}
      #       context: 'Test Results Link'
      #       state: 'success'
      #       sha: ${{ github.sha }}
      #       target_url: http://${{ secrets.AWS_S3_BUCKET }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com/index.html
      # - name: Display files and path
      #   run: |
      #     cd allure-results
      #     ls
      #     pwd
            
    
